### PR TITLE
feat(node): metrics

### PR DESCRIPTION
**Pull request by 3Hren**
# Work In Progress - Do not merge!
### Changelog
- Using metrics counters for both requests number counting and slaves
  spawning statistics.
- Add metrics service. Designed to serve as a provider to the internal metrics registry. It involves:
  - Obtaining metrics by name or/and tags.
  - Registering own metrics.
### Required to do
- [ ] Core provider support (#PR).
- [ ] Core metrics support (#PR).
- [ ] Metrics Module.
  - [x] Tagged metrics support (https://github.com/3Hren/metrics/commit/b9d41f0f080ef7157720fb0626911aab0f9ae9c0).
  - [x] Refactor metric wrappers (reduce boilerplate).
- [ ] Load testing (put relative results here %).
- [ ] Metrics service to be able to fetch any metrics by its tagged name.
  - [ ] List - list of all metrics registered.
  - [ ] Gauge (get).
  - [ ] Counter.
    - [x] Method: Get.
    - [ ] Method: Inc.
    - [ ] Method: Dec.
  - [ ] Meter.
    - [ ] Method: count.
    - [ ] Method: mark.
    - [ ] Methods: r01/r05/r15/mean.
  - [x] Timer (it's not trivial to implement modifiers, so not in this PR).
    - [x] Methods: pxx.
- [ ] Tools support (`cocaine-tool info --name=<service>`).

### CODE REVIEW

**Comment by 3Hren** [comment]
Tagged metrics - done: https://github.com/3Hren/metrics/commit/b9d41f0f080ef7157720fb0626911aab0f9ae9c0

**Comment by 3Hren** [comment]
Added metrics service. Implemented counters and timers getters.

**Comment by 3Hren** [comment]
Closed as reinventing the wheel

**Comment by kobolog** [comment]
Reopened due to @3Hren being a drama queen.

**Pull request closed without merging**
